# Generated by Django 3.2.3 on 2021-06-03 01:52

import MyFile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFile', '0002_alter_uploadfile_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='', validators=[MyFile.models.validate_file_extension], verbose_name='文件'),
        ),
    ]
