# Generated by Django 3.2.3 on 2021-06-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFile', '0003_alter_uploadfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='text',
            field=models.TextField(default='', verbose_name='markdown'),
        ),
    ]
