# Generated by Django 3.2.3 on 2021-06-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFile', '0004_uploadfile_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='markdown'),
        ),
    ]
