# Generated by Django 3.2.3 on 2021-06-14 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyFile', '0006_myword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myword',
            old_name='text',
            new_name='mark',
        ),
    ]
